services:
  rl:
    build: .
    container_name: rl_lunarlander
    environment:
      - PYGAME_HIDE_SUPPORT_PROMPT=1
      - SDL_VIDEODRIVER=dummy
      - MPLBACKEND=Agg
      - XDG_RUNTIME_DIR=/tmp
    volumes:
      - ./:/app
    ports:
      - "8888:8888"
    command: >
      bash -lc "pip install --no-cache-dir jupyterlab ipykernel &&
                jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --NotebookApp.token=''"
    restart: unless-stopped
